name: 1.0$(Rev:.r)
trigger:
- master
variables:
  name: makarand
pool:
  vmImage: ubuntu-latest
jobs:
  - job: A
    steps:
      - checkout: none
      - script: echo "Job A"
  - job: B
    dependsOn: A
    steps:
      - checkout: none
      - script: echo "Job B"
      