name: 1.0$(Rev:.r)
trigger:
  branches:
    include:
    - main
    exclude:
    - dev

variables:
  name: makarand
pool:
  vmImage: ubuntu-latest
jobs:
  - job: helloworld
    steps:
      - script: echo "Hello, $(name)"